## Data Science for Social Impact 
# Homework Monday: Python Basics, Lists, and Arrays

Please complete this notebook by filling in the cells provided. The solved homework should be uploaded to Gradescope on Canvas.

#### Deadline:

This assignment is due on **Monday at 11:30pm**.

Directly sharing answers is not okay, but discussing problems with eachother is encouraged!

In [ ]:
# Don't change this cell; just run it. 

import numpy as np

## Data Types

**Question 1.** When would you make a string using " " instead of ' '?

Replace this text with your answer

**Question 2.** What data type would you use to represent your bill at a restaurant?

Replace this text with your answer

**Question 3.** What data type would you use to represent whether a number is even or odd?

Replace this text with your answer

**Question 4.** Use a function to print the data type of the following variable:

In [ ]:
my_variable = '8.3'

In [ ]:
# Your code here

**Question 5.** Use a function to convert `my_variable` into a float.

In [ ]:
# Your code here

# Strings and Lists

Consider the list below:

In [ ]:
my_words = ["My", "I", "This", 'a', "She", 7, """am""", 89, "is", 'sentence', 'cup', 'dog', 'cute', 'love', '.', '!' ]

**Question 6.** Extract and slice from the list my_words to create the sentence: "This is a sentence." You can use list methods or operations.

In [ ]:
# Your code here

**Question 7.** Create an interesting sentence from my_words

In [ ]:
#Your code here

**Question 8.** Use the *replace* function for strings to change the string *'machine learning'* into the string *'learning machine'*. You must do everything into one line of code and you can only replace one full word with a different full word. An example of using *replace* twice in one line of code is below. [Note: the output should be a string of the same length as the one you started with; no extra spaces etc.]

In [ ]:
# this cell illustrates the use of .replace 
'Today is a good day.'.replace('.','!')

In [ ]:
# this cell illustrates the use of .replace twice
'on campus'.replace('on','happy').replace('campus','place')

In [ ]:
#Q8 code here

# Puzzles with Arrays

**Question 9.** Replace the ellipses in the following code to get the result 86

In [ ]:
my_array = np.array([1,2,3,4])
my_array2 = my_array * ...
my_array3 = my_array2 + ...
sum(my_array3)

**Question 10.** 

**a.** Create an array containing every 6th number between 7 and 700 inclusive (Hint: please do not type all of these numbers, use a function). 

**b.** Find the remainder after dividing each number by 7 (Hint: what operator can you use here). 

**c.** Then, take the average of the resulting numbers.

In [ ]:
# Your code here

**Question 11.**

**a.** Create an array called `four` that includes all integers from 1 to 120 (inclusive) in intervals of 4

**b.** Alter `four` to be a 5x5 array. Print the result.

**c.** Write code to select the highlighted numbers:

<br>

<div>
<img src="https://raw.githubusercontent.com/campbelle1/Introduction-to-Data-Science/main/Week%202/Array-exercise2.png"/>
</div>

**Question 12.** Sally is 5 ft 3in, 120 lbs. Create an expression that uses two variables: one called `height` (which equates to the value of Sally's height in inches) and called `weight` (which equates to the value of Sally's weight, in pounds). Using these variables, to calculate a Sally's BMI. The formula for BMI calculations are as follows:

weight (kg) รท height^2 (meters) * 703

Assign this calculation as `bmi`. <u>In one line of code</u>, print a statement that says:

"The BMI of this person is:

`bmi`."